# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboSerial = QtWidgets.QComboBox(self.centralwidget)
        self.comboSerial.setGeometry(QtCore.QRect(0, 20, 231, 22))
        self.comboSerial.setObjectName("comboSerial")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(250, 20, 75, 23))
        self.btnConnect.setObjectName("btnConnect")
        self.listData = QtWidgets.QListWidget(self.centralwidget)
        self.listData.setGeometry(QtCore.QRect(20, 180, 256, 192))
        self.listData.setObjectName("listData")
        self.labelClock = QtWidgets.QLabel(self.centralwidget)
        self.labelClock.setGeometry(QtCore.QRect(20, 80, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelClock.setFont(font)
        self.labelClock.setObjectName("labelClock")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(20, 150, 75, 23))
        self.btnStart.setObjectName("btnStart")
        self.btnStop = QtWidgets.QPushButton(self.centralwidget)
        self.btnStop.setGeometry(QtCore.QRect(120, 150, 75, 23))
        self.btnStop.setObjectName("btnStop")
        self.radioFreeMode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioFreeMode.setGeometry(QtCore.QRect(290, 220, 91, 31))
        self.radioFreeMode.setChecked(True)
        self.radioFreeMode.setObjectName("radioFreeMode")
        self.radioLapsMode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioLapsMode.setGeometry(QtCore.QRect(290, 250, 91, 31))
        self.radioLapsMode.setObjectName("radioLapsMode")
        self.checkFirstLap = QtWidgets.QCheckBox(self.centralwidget)
        self.checkFirstLap.setGeometry(QtCore.QRect(290, 190, 101, 21))
        self.checkFirstLap.setObjectName("checkFirstLap")
        self.spinLaps = QtWidgets.QSpinBox(self.centralwidget)
        self.spinLaps.setEnabled(True)
        self.spinLaps.setGeometry(QtCore.QRect(290, 290, 71, 22))
        self.spinLaps.setMinimum(1)
        self.spinLaps.setObjectName("spinLaps")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.radioFreeMode.toggled['bool'].connect(self.spinLaps.setHidden)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Easy Race"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.labelClock.setText(_translate("MainWindow", "00:00:00.000"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.radioFreeMode.setText(_translate("MainWindow", "Free Mode"))
        self.radioLapsMode.setText(_translate("MainWindow", "Laps Mode"))
        self.checkFirstLap.setText(_translate("MainWindow", "Start on first lap"))
